linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - module
    - style
    - test
    - unused
  disable:
    - golint
    - interfacer
    - scopelint
    - exhaustivestruct
    - maligned
