# spell-checker: disable

service:
  golangci-lint-version: 1.35.x

run:
  tests: true

linters:
  enable-all: true
  disable:
    # - funlen
    # - gochecknoglobals
    # - godox
    # - lll
    - wsl
