# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
universal_binaries:
  - replace: false
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - "darwin_amd64"
      - "darwin_arm64"

      - "windows_amd64"

      - "freebsd_amd64"
      - "freebsd_arm64"

      - "linux_amd64"
      - "linux_arm64"
      - "linux_arm_6"
      - "linux_386"
      - "linux_ppc64"
      - "linux_ppc64le"
archives:
  - id: default
    replacements:
      "darwin": "macos"
      "386": "i386"
  - id: binaries
    format: binary
    replacements:
      "darwin": "macos"
      "386": "i386"
brews:
  - ids:
      - "default"
    tap:
      owner: docwhat
      name: homebrew-tap
    commit_author:
      name: "goreleaserbot"
      email: "docwhat@users.noreply.github.com"
    test: |
      system "#{bin}/template --version"
      system "#{bin}/template /etc/hosts"
    install: |
      bin.install "template"
    folder: "Formula"
    homepage: "https://github.com/docwhat/temple"
    description: "Sick of sed? Prosaic about perl? Use temple to substitute your variables!"
    license: "MIT"
checksum:
  algorithm: sha256
  name_template: "checksums.sha256"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^travis:"
      - "^build:"
      - "^lint:"
      - "^style:"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
