#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

# shellcheck source=./utilities.bash
source "$(dirname "$0")/utilities.bash"

header "Fetching gox"
go get "$@" -v github.com/mitchellh/gox

header "Fetching gotestsum"
go get "$@" -v gotest.tools/gotestsum

header "Fetching golangci-lint"
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.35.2
bin/golangci-lint --version

# vim: set ft=sh :
