#!/bin/bash

#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

declare -i success=0 failure=0

yes() {
  success+=1
  echo '✅ '"$*"
}

no() {
  failure+=1
  echo '❌ '"$*"
}

if command -v 'golangci-lint' >/dev/null; then
  yes 'golangci-lint is present'
else
  no 'golangci-lont is missing'
fi

if ((failure > 0)); then
  echo "Fix the failures and run again."
  exit 1
fi

# vim: set ft=sh :
