#!/bin/bash
#
# Builds one (or more executable).
#
# Usage:
#   Just your native executable:
#      ./script/build
#   All cross compile platforms:
#      ./script/build all

set -euo pipefail
# shellcheck source=script/utilities.bash
source "$(dirname "$0")/utilities.bash"
progname="temple"

osarch="${1:-native}"
export CGO_ENABLED=0 # Force static compiling

version="$(git describe --tags || echo unreleased)"
ldflags="-s -w -X main.version=${version}"

if [[ "$osarch" == *all* ]]; then
  osarches=(
    darwin/amd64

    linux/386
    linux/amd64
    linux/arm
    linux/ppc64
    linux/ppc64le

    windows/386
    windows/amd64
  )

  header "Building all binaries"
  gox \
    -ldflags="$ldflags" \
    -osarch="${osarches[*]}" \
    -output='temple_{{.OS}}_{{.Arch}}'
else
  header "Building native binary"
  govendor build \
    -v \
    -ldflags "$ldflags" \
    -o "$progname" \
    +local
fi

# vim: set ft=sh :
