#!/bin/bash

set -euo pipefail

export CGO_ENABLED=0 # Force static compiling

version="$(git describe --tags || echo unreleased)"
ldflags="-s -w -X main.version=${version} -X main.commit=$(git rev-parse HEAD)"

go build -v -ldflags "${ldflags}" ./...

# vim: set ft=sh :
