#!/bin/bash
#
# Runs all lint.

set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
readonly root

x() {
  printf -- "+"
  printf -- " %q" "$@"
  printf -- "\n"
  "$@"
}

flags=()

if [[ -n ${CI-} ]]; then
  echo "Running lint in CI mode..."
  flags+=("--ci")
else
  echo "Running lint..."
fi

x "${root}/script/trunk" check "${flags[@]:+"${flags[@]}"}"

# vim: set ft=sh :
