#!/bin/bash
#
# Runs all tests.

set -euo pipefail
# shellcheck source=script/utilities.bash
source "$(dirname "$0")/utilities.bash"

header "Tests"
govendor test -v "$@" +local

header "Examples"
for example in examples/*; do
  if [ ! -d "$example" ]; then
    continue
  fi

  header "Example ${example}"
  # compgen -G is a badly documented trick to resolve wildcards into a
  # single file or an empty string.
  template=$(compgen -G "${example}"/*.template || :)
  json=$(compgen -G "${example}/*.json" || :)
  if [ -r "${json}" ]; then
    env RUNNING_WITH=json TODAY_IS="$(date)" go run ./*.go --json-data "$json" "$template"
  else
    env RUNNING_WITH=env TODAY_IS="$(date)" go run ./*.go "$template"
  fi
done

header "Linter"
gometalinter.v2 \
  --deadline=1m \
  --vendored-linters \
  --disable=gotype

# vim: set ft=sh :
